Closes #4
amino19/Health-Tracker pull request #5
Opened 2021-07-11 11:05 UTC by j-dogcoder

2021-07-11 11:05 UTC, j-dogcoder commented
Closes #4

2021-07-11 13:59 UTC, amino19 requested changes

2021-07-11 13:59 UTC, amino19 commented on README.md
> +## Show your support
@j-dogcoder : Can you pl put this section at bottom? :slightly_smiling_face:

2021-07-11 13:59 UTC, amino19 commented on README.md
> +👤 **amino19**
@j-dogcoder : Pl add <a href="https://github.com/amino19">that</a> link here, & remove the unorder-point from below! :slightly_smiling_face:

2021-07-11 13:59 UTC, amino19 commented on CONTRIBUTING.md
> +All contributors are welcome. Not sure where to start? Please follow the directions from the details given below, so you can get an idea of the project's workflow.
Pl don't mind to change this line as:
```
All contributors are welcome. Not sure where to start? Please follow the directions to simulate from the details given below, so you can get an idea of the project's workflow.
```

2021-07-11 13:59 UTC, amino19 commented on README.md
> +* Github: [@amino19](https://github.com/amino19)
@j-dogcoder : Pl remove this line, as it will be going to covered with `Line 23` :rocket:

2021-07-11 14:00 UTC, amino19 commented
@j-dogcoder : Almost done! :partying_face:

2021-07-11 17:13 UTC, j-dogcoder commented on CONTRIBUTING.md
> +All contributors are welcome. Not sure where to start? Please follow the directions from the details given below, so you can get an idea of the project's workflow.
Can you please clarify a bit @amino19?

2021-07-11 17:22 UTC, amino19 commented on CONTRIBUTING.md
> +All contributors are welcome. Not sure where to start? Please follow the directions from the details given below, so you can get an idea of the project's workflow.
@j-dogcoder : Copy paste the line in place of `Line 5` 🙂

2021-07-11 17:26 UTC, amino19 requested changes

2021-07-11 17:26 UTC, amino19 commented on README.md
> +## Show your support
@j-dogcoder : LGTM! 🎉

2021-07-11 17:55 UTC, amino19 commented
@j-dogcoder : Thanks Jasper for the hardwork! 
You made it somehow! :partying_face:

2021-07-11 17:55 UTC, merged

2021-07-11 17:56 UTC, j-dogcoder commented
🥳

2021-07-11 18:46 UTC, j-dogcoder commented
Anything else you need @amino19?

2021-07-11 18:46 UTC, j-dogcoder commented
I am going to install the project and give it a try.

2021-07-11 18:52 UTC, amino19 commented
@j-dogcoder : Actually it's not functional yet!

2021-07-11 18:53 UTC, j-dogcoder commented
Oh! You will have to let me know when it is!

2021-07-11 18:55 UTC, amino19 commented
@j-dogcoder : Do you mind to share me your contact panel, like via text social platform?

2021-07-11 18:56 UTC, j-dogcoder commented
My discord is J-dogcoder#0803

2021-07-12 13:54 UTC, amino19 commented
@j-dogcoder : Just sent you from `aminos 🇮🇳#2567` :slightly_smiling_face: